Repository NationalGenomicsInfrastructure/genomics-status, pull requests merged in 2023-09, with the labels that each got.

#770 Identify and link to ONT FCs in run notes too
  run_dir/static/js/base.js
Labels: no validation

#772 Add NovaSeqXPlus to qPCR and sequencing queues
  status/queues.py
Labels: no validation

#775 Added same sorting class to worksets page
  run_dir/design/worksets.html
Labels: no validation

#774 Updated DataTables to v. 1.13.6 for qPCR pools
  run_dir/design/qpcr_pools.html
  run_dir/static/js/dataTables-1.13.6.min.js
Labels: no validation

#771 Small fix to ONT FC page
  run_dir/design/ont_flowcells.html
  status/flowcell.py
Labels: bug, enhancement, no validation

#778 changed SNIC to NAISS
  run_dir/design/project_samples.html
Labels: no validation

#776 Uploaded DataTables file v. 1.13.6 with extensions to test and added Buttons extension to Worksets page
  run_dir/design/qpcr_pools.html
  run_dir/design/worksets.html
  run_dir/static/js/dataTables-1.13.6.min.js
  run_dir/static/js/dataTables-extensions-1.13.6.min.js
  run_dir/static/js/worksets.js
Labels: no validation

#779 Added blame ignore file
  .git-blame-ignore-revs
  requirements.txt
Labels: no validation

#780 Update DataTables to v 1.13.6 for flowcells page and add copy buttons extension
  run_dir/design/flowcells.html
  run_dir/design/ont_flowcells.html
Labels: no validation

#777 Enable automatic rendering of Highcharts plot on project select change
  run_dir/static/js/proj_meta_compare.js
Labels: no validation

#782 Updated DataTables to v 1.13.6 for a bunch of pages and Buttons ext. to seq qs
  run_dir/design/agreements_tab.html
  run_dir/design/index.html
  run_dir/design/instrument_logs.html
  run_dir/design/invoicing.html
  run_dir/design/libpooling_queues.html
  run_dir/design/pricing_preview.html
  run_dir/design/project_samples.html
  run_dir/design/projects.html
  run_dir/design/sample_requirements.html
  run_dir/design/sequencing_queues.html
  run_dir/design/user_management.html
  run_dir/design/workset_queues.html
  run_dir/static/js/sequencing_queues.js
Labels: no validation

#781 Switch Projects, flowcells, workset running notes to new db
  run_dir/design/deliveries.html
  run_dir/design/flowcells.html
  run_dir/design/worksets.html
  run_dir/static/js/base.js
  run_dir/static/js/project_samples.js
  run_dir/static/js/projects.js
  run_dir/static/js/running_notes.js
  run_dir/static/js/worksets.js
  status/deliveries.py
  status/flowcells.py
  status/projects.py
  status/queues.py
  status/running_notes.py
  status/worksets.py
  status_app.py
Labels: validation

#784 Hot Fix: Fix bug with default time in function parameters always returning the same time
  run_dir/static/js/running_notes.js
  status/running_notes.py
Labels: no validation

#785 Fix for NovaSeqXPlus ids on flowcells page
  run_dir/static/js/base.js
  status/flowcells.py
Labels: no validation

#786 Bugfix Use the 6 digit format of the date when looking it up on flowcells page
  status/running_notes.py
Labels: no validation

#783 Updated DataTables to v 1.13.6 and added the buttons extension to some pages
  run_dir/design/libpooling_queues.html
  run_dir/design/project_samples.html
  run_dir/design/projects.html
  run_dir/design/qpcr_pools.html
  run_dir/design/workset_queues.html
  run_dir/static/js/libpooling_queues.js
  run_dir/static/js/project_samples.js
  run_dir/static/js/projects.js
  run_dir/static/js/qpcr_pools.js
  run_dir/static/js/workset_queues.js
Labels: no validation

#787 Cleanup running notes on deliveries page
  run_dir/design/deliveries.html
  run_dir/static/js/deliveries.js
  run_dir/static/js/running_notes.js
  status/deliveries.py
Labels: no validation

#788 Add labels to latest running notes on various pages
  run_dir/design/flowcells.html
  run_dir/design/projects.html
  run_dir/design/workset_queues.html
  run_dir/design/worksets.html
  run_dir/static/css/status_b5.css
  run_dir/static/js/projects.js
  run_dir/static/js/workset_queues.js
  run_dir/static/js/worksets.js
Labels: no validation

#790 Add latest running note to qpcr queues
  run_dir/design/qpcr_pools.html
  run_dir/static/js/qpcr_pools.js
  status/queues.py
Labels: no validation
