Repository NationalGenomicsInfrastructure/genomics-status, pull requests merged in 2023-11, with the labels that each got.

#803 Fix indentation and change colors/novaseq lines cver
  run_dir/static/js/fc_trend_plot.js
Labels: no validation

#806 Division by zero bug for some nanopore run
  status/flowcell.py
Labels: no validation

#807 ONT error handling
  run_dir/design/flowcells.html
  status/flowcell.py
  status/flowcells.py
Labels: bug, enhancement, no validation

#808 Add nanopore to bp per week statistics
  status/statistics.py
Labels: no validation

#804 Change threshold value NovaSeqXPlus and add threshold lines to lane view
  run_dir/design/flowcell_trend_plot.html
  run_dir/static/js/fc_trend_plot.js
Labels: no validation

#810 Tiny fix parameter boxes
  run_dir/design/flowcell_trend_plot.html
Labels: no validation

#809 Split NovaSeq into 6000 and XPlus, removed HiSeq, and prettify parameter containers
  run_dir/design/data_delivered_plot.html
  run_dir/static/js/data_del_plot.js
Labels: no validation

#811 Bugfix, merging of dictionaries accidentialy overwrites illumina data
  status/statistics.py
Labels: no validation

#812 List initial loss of pores for ONT runs
  run_dir/design/ont_flowcells.html
  status/flowcell.py
  status/flowcells.py
Labels: enhancement, no validation

#813 Hide instrument name box unless color by instrument has been selected
  run_dir/static/js/fc_trend_plot.js
Labels: no validation

#814 Prettify instrument filter box depending on color type
  run_dir/static/js/fc_trend_plot.js
Labels: no validation
