Repository NationalGenomicsInfrastructure/genomics-status, pull requests merged in 2023-04, with the labels that each got.

#727 Removed blast wrapper from bioinfo tab
  run_dir/design/bioinfo_tab/run_lane_sample_view.html
  run_dir/design/bioinfo_tab/sample_run_lane_view.html
  run_dir/static/js/bioinfo_tab.js
Labels: no validation

#721 Fix calc crash for barcode runs w/o reads
  status/flowcell.py
Labels: bug, no validation

#729 Fix bug with Q30 value 0; change term actual lane yield into obtained
  run_dir/design/fc_project_yields_tab.html
  status/flowcell.py
Labels: bug, no validation

#730 Handle potential problem with 0 lane yield
  status/flowcell.py
Labels: enhancement, no validation

#731 Keep Vue and Axios locally instead of using fetching it online
  run_dir/design/agreements_tab.html
  run_dir/design/pricing_preview.html
  run_dir/design/pricing_quote.html
  run_dir/design/pricing_update.html
  run_dir/design/sample_requirements.html
  run_dir/design/sample_requirements_preview.html
  run_dir/design/sample_requirements_update.html
  run_dir/static/js/axios.v1.3.4.min.js
  run_dir/static/js/vue.v3.2.47.global.prod.js
Labels: no validation

#728 Serve MinKNOW report from local server dir
  status/flowcell.py
  status_app.py
Labels: enhancement, WIP, no validation

#732 Added invoicing running notes to agreements tab
  run_dir/design/agreement.html
  run_dir/design/agreements_tab.html
  run_dir/static/js/pricing_quote.js
  run_dir/static/js/running_notes.js
Labels: no validation

#733 Show login page without erroring out
  status/util.py
Labels: no validation
