Repository NationalGenomicsInfrastructure/genomics-status, pull requests merged in 2023-08, with the labels that each got.

#759 Flowcell trends changes
  run_dir/static/js/fc_trend_plot.js
  status/reads_plot.py
Labels: no validation

#760 Add more metrics for the ONT flowcells page
  run_dir/design/ont_flowcells.html
Labels: enhancement, no validation

#762 Improve column spacing, remove nonsencial search prompts and modify t…
  run_dir/design/ont_flowcells.html
Labels: enhancement, no validation

#761 Change to new running notes db for ONT FCs and projects
  run_dir/design/flowcell.html
  run_dir/design/ont_flowcell.html
  run_dir/static/js/flowcell.js
  run_dir/static/js/project_samples.js
  run_dir/static/js/running_notes.js
  status/projects.py
  status/running_notes.py
  status/worksets.py
  status_app.py
Labels: no validation

#763 Put back old run note urls for worksets and FCs other than ont
  run_dir/static/js/running_notes.js
Labels: no validation

#766 Stop int-only dir names crashing the regex query
  status/flowcell.py
Labels: bug, enhancement, no validation

#767 Tiniest fix for sorting ONT FCs
  run_dir/design/ont_flowcells.html
Labels: bug, no validation

#769 Replaced x with fa symbol in project meta samples comparison
  run_dir/static/js/proj_meta_compare.js
Labels: no validation

#768 Remove unused and deprecated apis
  status/production.py
  status/project_qc.py
  status_app.py
Labels: no validation
