Repository NationalGenomicsInfrastructure/genomics-status, pull requests merged in 2024-03, with the labels that each got.

#835 Remove redundant addition of script which was screwing with formatting
  run_dir/design/agreements_tab.html
Labels: no validation

#834 Highlight warnings last 24h for sensorpush and other changes for sensorpush
  run_dir/design/sensorpush.html
  run_dir/static/js/sensorpush.js
  status/sensorpush.py
Labels: no validation

#836 Functionality improvements in Agreements
  run_dir/design/agreement.html
  run_dir/static/js/pricing_quote.js
  run_dir/static/js/running_notes.js
  status/pricing.py
Labels: no validation

#837 Change q30 threshold values on reads aggregation page
  run_dir/design/reads_total.html
  run_dir/static/js/reads_total.js
  status/flowcells.py
Labels: no validation

#838 Fix for longer NovaSeqXPlus FC rundates
  status/flowcells.py
Labels: no validation

#840 Add NovaSeqXPlus 1.5b color to flowcells trends plot
  run_dir/static/js/fc_trend_plot.js
Labels: no validation

#841 Add preliminary lane yield threshold for NovaSeqXPlus 1.5B
  run_dir/static/js/fc_trend_plot.js
  status/flowcell.py
  status/flowcells.py
Labels: enhancement, no validation

#842 Set up more robust way of typing and handling barcode data
  status/flowcell.py
Labels: bug, no validation

#843 Fix flawed logic
  status/flowcell.py
Labels: bug, no validation

#844 Add color for coming 25B data to FC trends plot
  run_dir/static/js/fc_trend_plot.js
Labels: no validation

#845 Fix bug that weight Q30 for project per lane is not correct calculated
  status/flowcell.py
Labels: bug, no validation

#846 Fix bug that weight Q30 for aggregated sample is not correct calculated
  status/flowcell.py
Labels: bug, no validation
